In [27]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

In [28]:
obesitas_dataset = pd.read_csv('obesitas.csv')

In [29]:
obesitas_dataset.head()

Gender  Height  Weight  Index
0    Male     174      96      4
1    Male     189      87      2
2  Female     185     110      4
3  Female     195     104      3
4    Male     149      61      3

In [30]:
obesitas_dataset.shape

(500, 4)

In [31]:
obesitas_dataset['Index'].value_counts()

5    198
4    130
2     69
3     68
1     22
0     13
Name: Index, dtype: int64

In [32]:
# Membuat objek LabelEncoder
le = LabelEncoder()

# Menggunakan LabelEncoder untuk mengubah kolom 'Gender'
obesitas_dataset['Gender'] = le.fit_transform(obesitas_dataset['Gender'])

# Sekarang kolom 'Gender' berisi 0 dan 1
print(obesitas_dataset)

     Gender  Height  Weight  Index
0         1     174      96      4
1         1     189      87      2
2         0     185     110      4
3         0     195     104      3
4         1     149      61      3
..      ...     ...     ...    ...
495       0     150     153      5
496       0     184     121      4
497       0     141     136      5
498       1     150      95      5
499       1     173     131      5

[500 rows x 4 columns]


In [33]:
#memisahkan data dan label
X = obesitas_dataset.drop (columns = ['Index'], axis=1)
Y = obesitas_dataset['Index']

In [34]:
print(X)

     Gender  Height  Weight
0         1     174      96
1         1     189      87
2         0     185     110
3         0     195     104
4         1     149      61
..      ...     ...     ...
495       0     150     153
496       0     184     121
497       0     141     136
498       1     150      95
499       1     173     131

[500 rows x 3 columns]


In [35]:
print(Y)

0      4
1      2
2      4
3      3
4      3
      ..
495    5
496    4
497    5
498    5
499    5
Name: Index, Length: 500, dtype: int64


3. Standarisasi Data

In [36]:
scaler = StandardScaler()

In [50]:
scaler.fit(obesitas_dataset)

StandardScaler()

In [38]:
standarized_data = scaler.transform(obesitas_dataset)

In [39]:
print(standarized_data)

[[-1.02020406  0.24793878 -0.30911702  0.18615685]
 [-1.02020406  1.16487212 -0.58732233 -1.29127847]
 [ 0.98019606  0.92035656  0.12364681  0.18615685]
 ...
 [ 0.98019606 -1.76931458  0.92735105  0.92487451]
 [-1.02020406 -1.21915457 -0.34002872  0.92487451]
 [-1.02020406  0.18680989  0.77279254  0.92487451]]


In [40]:
X = standarized_data
Y = obesitas_dataset['Index']

In [41]:
print(X)
print(Y)

[[-1.02020406  0.24793878 -0.30911702  0.18615685]
 [-1.02020406  1.16487212 -0.58732233 -1.29127847]
 [ 0.98019606  0.92035656  0.12364681  0.18615685]
 ...
 [ 0.98019606 -1.76931458  0.92735105  0.92487451]
 [-1.02020406 -1.21915457 -0.34002872  0.92487451]
 [-1.02020406  0.18680989  0.77279254  0.92487451]]
0      4
1      2
2      4
3      3
4      3
      ..
495    5
496    4
497    5
498    5
499    5
Name: Index, Length: 500, dtype: int64


4. Memisahkan Data Training dan Data Testing

In [42]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [43]:
print(X.shape, X_train.shape, X_test.shape)

(500, 4) (400, 4) (100, 4)


5.  Membuat dan melatih model LinearSVC

In [44]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

# Membaca data dari file CSV
df = pd.read_csv('data_hasil.csv')  # Ganti 'data_hasil.csv' dengan nama file CSV yang sesuai

# Memisahkan fitur (X) dan target (Y)
X = df[['Gender', 'Height', 'Weight']]
Y = df['Index']  # Kolom 'Index' adalah target Anda

# Skala data
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Bagi data menjadi data pelatihan dan data uji
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

# Membuat dan melatih model LinearSVC
model = LinearSVC(dual=False)
model.fit(X_train, Y_train)

# Melakukan prediksi pada data uji
Y_test_prediction = model.predict(X_test)

# Mengukur akurasi pada data uji
test_data_accuracy = accuracy_score(Y_test, Y_test_prediction)

# Menampilkan akurasi
print(f"Akurasi pada data uji: {test_data_accuracy}")


Akurasi pada data uji: 0.78


6. Membuat model evaluasi untuk mengukur tingkat akurasi

In [45]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [46]:
print('Akurasi data training adalah = ', training_data_accuracy)

Akurasi data training adalah =  0.6825


In [47]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [48]:
print('Akurasi data testing adalah = ', test_data_accuracy)

Akurasi data testing adalah =  0.78


7. Membuat Model Prediksi

In [49]:
import numpy as np
from sklearn.preprocessing import StandardScaler

# Membuat objek StandardScaler
scaler = StandardScaler()

# Latih scaler pada data latih yang memiliki 3 fitur (Height, Weight, Gender)
X_train = df[['Height', 'Weight', 'Gender']]
scaler.fit(X_train)


# Sekarang, gunakan scaler untuk mentransformasi data baru
input_data = (174, 96, 1)  # Ubah urutan sesuai dengan kolom Anda: Height, Weight, Gender
input_data_as_numpy_array = np.array([input_data])  # Memberikan nama fitur sesuai urutan
std_data = scaler.transform(input_data_as_numpy_array)



# Melakukan prediksi pada data yang telah di-scaling
prediction = model.predict(std_data)

# Mengekstraksi hasil prediksi
predicted_class = prediction[0]

# Menerjemahkan hasil prediksi menjadi label
if predicted_class == 0:
    print('Sangat kurus')
elif predicted_class == 1:
    print('kurus')
elif predicted_class == 2:
    print('Normal')
elif predicted_class == 3:
    print('Gemuk')
elif predicted_class == 4:
    print('Obesitas')
else:
    print('Obesitas akut')

Obesitas akut


c:\Users\Mahsa\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
